changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "## Changed"
      labels: 
        - "Type: Feature"
    - title: "## Fixed"
      labels:
        - "Type: Bug"
    - title: "## Other Changes"
      labels:
        - "*"
